language: python
python:
  - "3.6"
install:
  - pip install -r requirements-dev.txt
script:
  - tools/get-credentials
  - pytest --cov=api
cache: pip

after_success:
  - codecov
  
branches:
  only:
  - master
  - dev
