#!/usr/bin/env sh

. $(dirname "$0")/../.env

mkdir -p res/credentials
curl --user ${REMOTE_DATA_LOGIN}:${REMOTE_DATA_PASSWD} https://suri.customer.berdy.pro/credentials/surirobotSTT.json -o res/credentials/google.json
curl --user ${REMOTE_DATA_LOGIN}:${REMOTE_DATA_PASSWD} https://suri.customer.berdy.pro/credentials/surirobotTTS.json -o res/credentials/ibm.json
