#!/usr/bin/env sh
SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
if [ -f ${SCRIPTPATH}/../.env ]; then
    . ${SCRIPTPATH}/../.env
fi
echo ${SCRIPTPATH}/../.env
mkdir -p ${SCRIPTPATH}/../res/credentials
curl --user ${REMOTE_DATA_LOGIN}:${REMOTE_DATA_PASSWD} https://files.api.suricats-consulting.com/credentials/surirobotSTT.json -o "$( cd "$(dirname "$0")" ; pwd -P )"/../res/credentials/google.json
curl --user ${REMOTE_DATA_LOGIN}:${REMOTE_DATA_PASSWD} https://files.api.suricats-consulting.com/credentials/surirobotTTS.json -o "$( cd "$(dirname "$0")" ; pwd -P )"/../res/credentials/ibm.json
curl --user ${REMOTE_DATA_LOGIN}:${REMOTE_DATA_PASSWD} https://files.api.suricats-consulting.com/credentials/surirobotNLP.json -o "$( cd "$(dirname "$0")" ; pwd -P )"/../res/credentials/recast.json
